spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codelist
    username: torgravels
    password: torgravels
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true