spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codelist
    username: torgravels
    password: torgravels
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml

  flyway:
    enabled: true