spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codelist
    username: torgravels
    password: torgravels

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder=TRACE: